return path
mazoea/pyi2t pull request #5
Opened 2022-05-17 15:27 UTC by TooMindoo

2022-05-23 20:43 UTC, vidiecan requested changes

2022-05-23 20:43 UTC, vidiecan commented on pysrc/i2t.py
> +        self.path = None
why not `_path`?

2022-05-24 07:51 UTC, TooMindoo commented on pysrc/i2t.py
> +        self.path = None
renamed

2022-05-24 21:25 UTC, vidiecan approved these changes

2022-05-25 06:30 UTC, merged