Hotfix to be able to build with new version of visual studio
mazoea/pyi2t pull request #6
Opened 2022-06-21 11:03 UTC by josop-5

2022-06-21 13:58 UTC, vidiecan requested changes

2022-06-21 13:58 UTC, vidiecan commented on src/pylib.h
> +#include "os/msvc_error_hotfix.h"
```suggestion
#include "os/compilers.h"
```

2022-06-21 14:08 UTC, ku-bo approved these changes

2022-06-24 07:29 UTC, vidiecan approved these changes

2022-06-24 08:17 UTC, merged